import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import {
  NextUIProvider,
  ReduxProvider,
  TanstackProvider,
  ToastProvider,
} from '../providers';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextUIProvider>
          <ClerkProvider>
            <ReduxProvider>
              <TanstackProvider>
                <ToastProvider>{children}</ToastProvider>
                <ToastContainer />
              </TanstackProvider>
            </ReduxProvider>
          </ClerkProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
