import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ToastContainer } from 'react-toastify';
import { NextUIProvider, TanstackProvider, ToastProvider } from '../providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextUIProvider>
          <TanstackProvider>
            <ToastProvider>{children}</ToastProvider>
            <ToastContainer />
          </TanstackProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
