import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify'
import { NextUIProvider, TanstackProvider, ToastProvider } from '../providers'
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={inter.className}>
          <NextUIProvider>
            <TanstackProvider>
              <ToastProvider>
                {/* <SignedOut>
                  <SignInButton />
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn> */}
                {children}
                <ToastContainer />
              </ToastProvider>
            </TanstackProvider>
          </NextUIProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}